[package]
name = "jester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.21"
argfile = "0.1.4"
wild = "2.1.0"