api_key: ""
api_secret: ""
deep_lynx_url: ""
directories:
  - path: "one"
    files:
      - data_source_id: 1
        container_id: 1
        metadata_data_source_id: 1
        pattern: "*"
  - path: "two"
    files:
      - data_source_id: 2
        container_id: 1
        metadata_data_source_id: 1
        pattern: "*"
