api_key: ""
api_secret: ""
deep_lynx_url: "http://localhost:8090"
files:
  - timeseries_data_source_id: 469
    container_id: 1
    path_pattern: "./sample_dir/*.csv"
  - timeseries_data_source_id: 1146
    container_id: 1
    path_pattern: "./sample_dir/*.json"